export const blackCards = [
  { id: "black-001", text: "The real reason my camera is off is ______.", type: 'black' as const, pick: 1 },
  { id: "black-002", text: "Nothing destroys productivity faster than ______.", type: 'black' as const, pick: 1 },
  { id: "black-003", text: "My toxic remote-work trait is ______.", type: 'black' as const, pick: 1 },
  { id: "black-004", text: "The quickest way to create chaos in a meeting is ______.", type: 'black' as const, pick: 1 },
  { id: "black-005", text: "Nothing says \"professionalism\" like ______.", type: 'black' as const, pick: 1 },
  { id: "black-006", text: "The unofficial Team Raydiant motto is ______.", type: 'black' as const, pick: 1 },
  { id: "black-007", text: "The real reason the meeting went 20 minutes over was ______.", type: 'black' as const, pick: 1 },
  { id: "black-008", text: "Nothing says \"this could've been an email\" like ______.", type: 'black' as const, pick: 1 },
  { id: "black-009", text: "Glowbert's secret side hustle is ______.", type: 'black' as const, pick: 1 },
  { id: "black-010", text: "Glowbert's villain origin story started with ______.", type: 'black' as const, pick: 1 },
  { id: "black-011", text: "The final boss of Team Raydiant is ______.", type: 'black' as const, pick: 1 },
  { id: "black-012", text: "Glowbert's browser history definitely contains ______.", type: 'black' as const, pick: 1 },
  { id: "black-013", text: "Glowbert's next expansion pack features ______.", type: 'black' as const, pick: 1 },
  { id: "black-014", text: "The real power behind Team Raydiant is ______.", type: 'black' as const, pick: 1 },
  { id: "black-015", text: "Glowbert's biggest weakness is ______.", type: 'black' as const, pick: 1 },
  { id: "black-016", text: "I've got 99 problems but ______ ain't one.", type: 'black' as const, pick: 1 },
  { id: "black-017", text: "50% of all student calls end with ______.", type: 'black' as const, pick: 1 },
  { id: "black-018", text: "I don't always ______, but I definitely do after speaking with a 0-TP student.", type: 'black' as const, pick: 1 },
  { id: "black-019", text: "A mentor's best friend is ______.", type: 'black' as const, pick: 1 },
  { id: "black-020", text: "My student graduated and now I'm ______.", type: 'black' as const, pick: 1 },
  { id: "black-021", text: "My student withdrew because ______.", type: 'black' as const, pick: 1 },
  { id: "black-022", text: "The wildest excuse I've ever heard involved ______.", type: 'black' as const, pick: 1 },
  { id: "black-023", text: "My student promised they'd start studying after ______.", type: 'black' as const, pick: 1 },
  { id: "black-024", text: "The student insisted the problem was ______.", type: 'black' as const, pick: 1 },
  { id: "black-025", text: "Every mentor eventually learns the true meaning of ______.", type: 'black' as const, pick: 1 },
  { id: "black-026", text: "I answered all my emails, and now it's time to ______.", type: 'black' as const, pick: 1 },
  { id: "black-027", text: "The word or phrase I hate most in meetings is ______.", type: 'black' as const, pick: 1 },
  { id: "black-028", text: "Corporate's solution to every problem is ______.", type: 'black' as const, pick: 1 },
  { id: "black-029", text: "Every migration somehow becomes ______.", type: 'black' as const, pick: 1 },
  { id: "black-030", text: "The real purpose of admin time is ______.", type: 'black' as const, pick: 1 },
  { id: "black-031", text: "My Outlook calendar is powered entirely by ______.", type: 'black' as const, pick: 1 },
  { id: "black-032", text: "My call notes accidentally turned into ______.", type: 'black' as const, pick: 1 },
  { id: "black-033", text: "HR specifically asked us to stop ______.", type: 'black' as const, pick: 1 },
  { id: "black-034", text: "The group chat peaked when someone posted ______.", type: 'black' as const, pick: 1 },
  { id: "black-035", text: "The most threatening sentence is: \"Can you stay after the meeting to discuss ______?\"", type: 'black' as const, pick: 1 },
  { id: "black-036", text: "My autobiography would be titled \"______.\"", type: 'black' as const, pick: 1 },
  { id: "black-037", text: "My emotional support item is ______.", type: 'black' as const, pick: 1 },
  { id: "black-038", text: "Nothing says \"I have my life together\" like ______.", type: 'black' as const, pick: 1 },
  { id: "black-039", text: "My villain origin story began with ______.", type: 'black' as const, pick: 1 },
  { id: "black-040", text: "My toxic trait is thinking ______.", type: 'black' as const, pick: 1 },
  { id: "black-041", text: "The real reason I need PTO is ______.", type: 'black' as const, pick: 1 },
  { id: "black-042", text: "The quickest way to become a Team Raydiant legend is ______.", type: 'black' as const, pick: 1 }
]
