export const blackCards = [
  { id: "black-001", text: "The real reason my camera is off is ______.", type: 'black' as const, pick: 1 },
  { id: "black-002", text: "Nothing destroys productivity faster than ______.", type: 'black' as const, pick: 1 },
  { id: "black-003", text: "My toxic remote-work trait is ______.", type: 'black' as const, pick: 1 },
  { id: "black-004", text: "The most suspicious Teams message is: \"______.\"", type: 'black' as const, pick: 1 },
  { id: "black-005", text: "The quickest way to create chaos in a meeting is ______.", type: 'black' as const, pick: 1 },
  { id: "black-006", text: "My brain immediately shuts down when someone says ______.", type: 'black' as const, pick: 1 },
  { id: "black-007", text: "The most emotionally devastating Outlook notification is ______.", type: 'black' as const, pick: 1 },
  { id: "black-008", text: "Nothing says \"professionalism\" like ______.", type: 'black' as const, pick: 1 },
  { id: "black-009", text: "The unofficial Team Raydiant motto is ______.", type: 'black' as const, pick: 1 },
  { id: "black-010", text: "The real reason the meeting went 20 minutes over was ______.", type: 'black' as const, pick: 1 },
  { id: "black-011", text: "Nothing says \"this could've been an email\" like ______.", type: 'black' as const, pick: 1 },
  { id: "black-012", text: "The fastest way to emotionally recover from a meeting is ______.", type: 'black' as const, pick: 1 },
  { id: "black-013", text: "The unofficial symptom of burnout is ______.", type: 'black' as const, pick: 1 },
  { id: "black-014", text: "The strongest form of workplace communication is ______.", type: 'black' as const, pick: 1 },
  { id: "black-015", text: "The most cursed thing to put in a PowerPoint is ______.", type: 'black' as const, pick: 1 },
  { id: "black-016", text: "Glowbert's official leadership strategy is ______.", type: 'black' as const, pick: 1 },
  { id: "black-017", text: "Glowbert's secret side hustle is ______.", type: 'black' as const, pick: 1 },
  { id: "black-018", text: "Glowbert's villain origin story started with ______.", type: 'black' as const, pick: 1 },
  { id: "black-019", text: "The final boss of Team Raydiant is ______.", type: 'black' as const, pick: 1 },
  { id: "black-020", text: "Glowbert's browser history definitely contains ______.", type: 'black' as const, pick: 1 },
  { id: "black-021", text: "The hidden level of Team Raydiant unlocks after ______.", type: 'black' as const, pick: 1 },
  { id: "black-022", text: "Glowbert's emergency response plan includes ______.", type: 'black' as const, pick: 1 },
  { id: "black-023", text: "Glowbert's next expansion pack features ______.", type: 'black' as const, pick: 1 },
  { id: "black-024", text: "The real power behind Team Raydiant is ______.", type: 'black' as const, pick: 1 },
  { id: "black-025", text: "Glowbert's biggest weakness is ______.", type: 'black' as const, pick: 1 },
  { id: "black-026", text: "I've got 99 problems but ______ ain't one.", type: 'black' as const, pick: 1 },
  { id: "black-027", text: "Fifty percent of all student calls end with ______.", type: 'black' as const, pick: 1 },
  { id: "black-028", text: "I never understood ______ until I had ______.", type: 'black' as const, pick: 2 },
  { id: "black-029", text: "I don't always ______, but I definitely do after speaking with a 0 TP student.", type: 'black' as const, pick: 1 },
  { id: "black-030", text: "A student's best friend is ______.", type: 'black' as const, pick: 1 },
  { id: "black-031", text: "A mentor's best friend is ______.", type: 'black' as const, pick: 1 },
  { id: "black-032", text: "The only thing keeping this student enrolled is ______.", type: 'black' as const, pick: 1 },
  { id: "black-033", text: "My student graduated and now I'm ______.", type: 'black' as const, pick: 1 },
  { id: "black-034", text: "My student withdrew because ______.", type: 'black' as const, pick: 1 },
  { id: "black-035", text: "The wildest excuse I've ever heard involved ______.", type: 'black' as const, pick: 1 },
  { id: "black-036", text: "My student promised they'd start studying after ______.", type: 'black' as const, pick: 1 },
  { id: "black-037", text: "The student insisted the problem was ______.", type: 'black' as const, pick: 1 },
  { id: "black-038", text: "The real prerequisite for success at WGU is ______.", type: 'black' as const, pick: 1 },
  { id: "black-039", text: "Every mentor eventually learns the true meaning of ______.", type: 'black' as const, pick: 1 },
  { id: "black-040", text: "The student swore they were \"just about to\" ______.", type: 'black' as const, pick: 1 },
  { id: "black-041", text: "I answered all my emails, and now it's time to ______.", type: 'black' as const, pick: 1 },
  { id: "black-042", text: "I deserve ______ after today.", type: 'black' as const, pick: 1 },
  { id: "black-043", text: "I heard we're doing yet another ______.", type: 'black' as const, pick: 1 },
  { id: "black-044", text: "The word or phrase I hate most in meetings is ______.", type: 'black' as const, pick: 1 },
  { id: "black-045", text: "Corporate's solution to every problem is ______.", type: 'black' as const, pick: 1 },
  { id: "black-046", text: "Every migration somehow becomes ______.", type: 'black' as const, pick: 1 },
  { id: "black-047", text: "The real purpose of admin time is ______.", type: 'black' as const, pick: 1 },
  { id: "black-048", text: "My Outlook calendar is powered entirely by ______.", type: 'black' as const, pick: 1 },
  { id: "black-049", text: "My call notes accidentally turned into ______.", type: 'black' as const, pick: 1 },
  { id: "black-050", text: "The pilot program unexpectedly became ______.", type: 'black' as const, pick: 1 },
  { id: "black-051", text: "My 4:59 PM meeting is secretly about ______.", type: 'black' as const, pick: 1 },
  { id: "black-052", text: "HR specifically asked us to stop ______.", type: 'black' as const, pick: 1 },
  { id: "black-053", text: "The group chat peaked when someone posted ______.", type: 'black' as const, pick: 1 },
  { id: "black-054", text: "The most dangerous phrase in existence is: \"It'll only take ______.\"", type: 'black' as const, pick: 1 },
  { id: "black-055", text: "The most threatening sentence is: \"Can you stay after the meeting to discuss ______?\"", type: 'black' as const, pick: 1 },
  { id: "black-056", text: "My autobiography would be titled \"______.\"", type: 'black' as const, pick: 1 },
  { id: "black-057", text: "My emotional support item is ______.", type: 'black' as const, pick: 1 },
  { id: "black-058", text: "Nothing says \"I have my life together\" like ______.", type: 'black' as const, pick: 1 },
  { id: "black-059", text: "My personal warning label would read: \"Caution: ______.\"", type: 'black' as const, pick: 1 },
  { id: "black-060", text: "My villain origin story began with ______.", type: 'black' as const, pick: 1 },
  { id: "black-061", text: "My toxic trait is thinking ______.", type: 'black' as const, pick: 1 },
  { id: "black-062", text: "The real reason I need PTO is ______.", type: 'black' as const, pick: 1 },
  { id: "black-063", text: "If this meeting had a post-credit scene, it would include ______.", type: 'black' as const, pick: 1 },
  { id: "black-064", text: "Scientists still can't explain ______.", type: 'black' as const, pick: 1 },
  { id: "black-065", text: "The quickest way to become a Team Raydiant legend is ______.", type: 'black' as const, pick: 1 }
]
