export const whiteCards = [
  { id: "white-001", text: "an emotionally devastating Outlook notification", type: 'white' as const },
  { id: "white-002", text: "pretending I understood the assignment", type: 'white' as const },
  { id: "white-003", text: "twenty-seven unread Teams messages", type: 'white' as const },
  { id: "white-004", text: "fake productivity", type: 'white' as const },
  { id: "white-005", text: "panic-clicking \"Share Screen\"", type: 'white' as const },
  { id: "white-006", text: "saying \"you're on mute\" with confidence", type: 'white' as const },
  { id: "white-007", text: "typing noises for intimidation", type: 'white' as const },
  { id: "white-008", text: "muting myself and still talking", type: 'white' as const },
  { id: "white-009", text: "a calendar invite with no context", type: 'white' as const },
  { id: "white-010", text: "reopening the same spreadsheet fourteen times", type: 'white' as const },
  { id: "white-011", text: "one unstable Wi-Fi connection", type: 'white' as const },
  { id: "white-012", text: "the \"quick question\" that ruined my afternoon", type: 'white' as const },
  { id: "white-013", text: "replying \"sounds good!\" without reading anything", type: 'white' as const },
  { id: "white-014", text: "aggressively nodding while confused", type: 'white' as const },
  { id: "white-015", text: "staring into the void between meetings", type: 'white' as const },
  { id: "white-016", text: "a deeply personal vendetta against Outlook", type: 'white' as const },
  { id: "white-017", text: "accidentally replying all", type: 'white' as const },
  { id: "white-018", text: "pretending the system is loading", type: 'white' as const },
  { id: "white-019", text: "one emotional support spreadsheet", type: 'white' as const },
  { id: "white-020", text: "weaponized silence", type: 'white' as const },
  { id: "white-021", text: "passive-aggressive professionalism", type: 'white' as const },
  { id: "white-022", text: "crying in business casual", type: 'white' as const },
  { id: "white-023", text: "\"just one quick thing\"", type: 'white' as const },
  { id: "white-024", text: "Outlook gaslighting me", type: 'white' as const },
  { id: "white-025", text: "inbox bankruptcy", type: 'white' as const },
  { id: "white-026", text: "one inactive student", type: 'white' as const },
  { id: "white-027", text: "five inactive students", type: 'white' as const },
  { id: "white-028", text: "another pilot program", type: 'white' as const },
  { id: "white-029", text: "unnecessary migration", type: 'white' as const },
  { id: "white-030", text: "Version 7 of the same course", type: 'white' as const },
  { id: "white-031", text: "excessive documentation", type: 'white' as const },
  { id: "white-032", text: "one more Salesforce note", type: 'white' as const },
  { id: "white-033", text: "term planning gone sideways", type: 'white' as const },
  { id: "white-034", text: "\"I already emailed my mentor.\"", type: 'white' as const },
  { id: "white-035", text: "\"Canvas was down.\"", type: 'white' as const },
  { id: "white-036", text: "\"I thought the OA was optional.\"", type: 'white' as const },
  { id: "white-037", text: "an enrollment date from 2019", type: 'white' as const },
  { id: "white-038", text: "one mysteriously missing webcam", type: 'white' as const },
  { id: "white-039", text: "twelve unfinished degree plans", type: 'white' as const },
  { id: "white-040", text: "a surprise program change", type: 'white' as const },
  { id: "white-041", text: "mass emails", type: 'white' as const },
  { id: "white-042", text: "inbox overload", type: 'white' as const },
  { id: "white-043", text: "excessive notes", type: 'white' as const },
  { id: "white-044", text: "\"We're refreshing the curriculum.\"", type: 'white' as const },
  { id: "white-045", text: "a student who \"just has one quick question\"", type: 'white' as const },
  { id: "white-046", text: "Glowbert's villain era", type: 'white' as const },
  { id: "white-047", text: "Glowbert After Dark", type: 'white' as const },
  { id: "white-048", text: "Glowbert's emotional support honey", type: 'white' as const },
  { id: "white-049", text: "Glowbert's burner Teams account", type: 'white' as const },
  { id: "white-050", text: "Glowbert pretending to be offline", type: 'white' as const },
  { id: "white-051", text: "Glowbert's leadership podcast", type: 'white' as const },
  { id: "white-052", text: "Glowbert's suspicious search history", type: 'white' as const },
  { id: "white-053", text: "Glowbert's tiny business casual tie", type: 'white' as const },
  { id: "white-054", text: "the consequences of my own actions", type: 'white' as const },
  { id: "white-055", text: "one perfectly timed meme", type: 'white' as const },
  { id: "white-056", text: "confidence unsupported by evidence", type: 'white' as const },
  { id: "white-057", text: "accidental leadership", type: 'white' as const },
  { id: "white-058", text: "a suspicious amount of confidence", type: 'white' as const },
  { id: "white-059", text: "pretending everything is under control", type: 'white' as const },
  { id: "white-060", text: "caffeine and denial", type: 'white' as const },
  { id: "white-061", text: "checking Teams status like it's the stock market", type: 'white' as const },
  { id: "white-062", text: "overcommitting during a brief moment of motivation", type: 'white' as const },
  { id: "white-063", text: "one unnecessary follow-up meeting", type: 'white' as const },
  { id: "white-064", text: "\"per my last email\"", type: 'white' as const },
  { id: "white-065", text: "\"Happy Monday!\"", type: 'white' as const },
  { id: "white-066", text: "one deeply cursed notification sound", type: 'white' as const },
  { id: "white-067", text: "an action item with no owner", type: 'white' as const },
  { id: "white-068", text: "corporate optimism", type: 'white' as const },
  { id: "white-069", text: "scream at the top of my lungs", type: 'white' as const },
  { id: "white-070", text: "party until I drop", type: 'white' as const },
  { id: "white-071", text: "the magic of wishful thinking", type: 'white' as const },
  { id: "white-072", text: "so happy I could cry", type: 'white' as const },
  { id: "white-073", text: "so happy I'll never have to see them again", type: 'white' as const },
  { id: "white-074", text: "running a marathon", type: 'white' as const },
  { id: "white-075", text: "a complete psychological collapse at 4:47 PM", type: 'white' as const },
  { id: "white-076", text: "one functioning brain cell", type: 'white' as const },
  { id: "white-077", text: "raw panic", type: 'white' as const },
  { id: "white-078", text: "a highly questionable life choice", type: 'white' as const },
  { id: "white-079", text: "a complete lack of work-life balance", type: 'white' as const },
  { id: "white-080", text: "muting myself to talk trash", type: 'white' as const },
  { id: "white-081", text: "a motivational quote nobody asked for", type: 'white' as const },
  { id: "white-082", text: "one browser tab away from greatness", type: 'white' as const },
  { id: "white-083", text: "writing my entire self-review with ChatGPT", type: 'white' as const },
  { id: "white-084", text: "confidently selecting \"Exceeds\" based on vibes alone", type: 'white' as const },
  { id: "white-085", text: "justifying a \"Role Model\" rating with vibes alone", type: 'white' as const },
  { id: "white-086", text: "explaining away one bad metric", type: 'white' as const },
  { id: "white-087", text: "hoping nobody reads my self-review examples too closely", type: 'white' as const },
  { id: "white-088", text: "making one accomplishment sound like an organizational transformation", type: 'white' as const },
  { id: "white-089", text: "accidentally describing someone else's accomplishment in my self-review", type: 'white' as const },
  { id: "white-090", text: "one beautifully written paragraph in my self-review that says absolutely nothing", type: 'white' as const },
  { id: "white-091", text: "pretending I remembered every action item from my last 1:1", type: 'white' as const },
  { id: "white-092", text: "saying \"Nope, I'm doing great!\" while absolutely not doing great", type: 'white' as const },
  { id: "white-093", text: "my manager asking, \"What's on your mind today?\"", type: 'white' as const },
  { id: "white-094", text: "awkward silence after, \"Any questions?\"", type: 'white' as const },
  { id: "white-095", text: "spending the first five minutes trying to remember why we scheduled this", type: 'white' as const },
  { id: "white-096", text: "\"Let's revisit that next month.\"", type: 'white' as const },
  { id: "white-097", text: "one development opportunity I wasn't emotionally prepared for", type: 'white' as const },
  { id: "white-098", text: "accidentally oversharing in my 1:1", type: 'white' as const },
  { id: "white-099", text: "aggressively nodding while taking fake notes", type: 'white' as const },
  { id: "white-100", text: "hearing \"I have some feedback...\" at 8:01 AM", type: 'white' as const },
  { id: "white-101", text: "my manager saying, \"I've noticed a pattern...\"", type: 'white' as const },
  { id: "white-102", text: "one follow-up to the follow-up from our last follow-up", type: 'white' as const },
  { id: "white-103", text: "smiling through constructive feedback", type: 'white' as const },
  { id: "white-104", text: "\"Tell me more about that...\"", type: 'white' as const },
  { id: "white-105", text: "pretending I wasn't just called out", type: 'white' as const },
  { id: "white-106", text: "writing exactly enough to look reflective  in my Reflection Notebook", type: 'white' as const },
  { id: "white-107", text: "copying last month's reflection in my Reflection Notebook and changing a few words", type: 'white' as const },
  { id: "white-108", text: "discovering personal growth with five minutes left before the deadline", type: 'white' as const },
  { id: "white-109", text: "therapeutic bullet points", type: 'white' as const },
  { id: "white-110", text: "fake vulnerability for professional development", type: 'white' as const },
  { id: "white-111", text: "writing what I think my manager hopes I'll write in my Reflection Notebook", type: 'white' as const },
  { id: "white-112", text: "one emotionally profound sentence followed by three paragraphs of filler", type: 'white' as const },
  { id: "white-113", text: "reflecting on things I definitely won't change", type: 'white' as const },
  { id: "white-114", text: "journaling because it's apparently good for me", type: 'white' as const },
  { id: "white-115", text: "\"This month I challenged myself...\"", type: 'white' as const },
  { id: "white-116", text: "one suspiciously well-written reflection", type: 'white' as const },
  { id: "white-117", text: "asking AI to make me sound more self-aware", type: 'white' as const },
  { id: "white-118", text: "accidentally having a real breakthrough", type: 'white' as const },
  { id: "white-119", text: "growth mindset... but make it corporate", type: 'white' as const },
  { id: "white-120", text: "asking ChatGPT to make me sound less passive aggressive", type: 'white' as const },
  { id: "white-121", text: "asking ChatGPT to explain my own email back to me", type: 'white' as const },
  { id: "white-122", text: "forgetting to GlowScrub before GlowNotes", type: 'white' as const },
  { id: "white-123", text: "GlowNotes writing a better email than I ever could", type: 'white' as const },
  { id: "white-124", text: "one suspiciously perfect student outreach email", type: 'white' as const },
  { id: "white-125", text: "ChatGPT saving me from Outlook", type: 'white' as const },
  { id: "white-126", text: "arguing with AI over one sentence for twenty minutes", type: 'white' as const },
  { id: "white-127", text: "asking AI to summarize a meeting I attended", type: 'white' as const },
  { id: "white-128", text: "asking AI to rewrite something five different ways", type: 'white' as const },
  { id: "white-129", text: "AI hallucinating an entire student conversation", type: 'white' as const },
  { id: "white-130", text: "one copy-and-paste masterpiece", type: 'white' as const },
  { id: "white-131", text: "pretending I totally wrote that myself", type: 'white' as const },
  { id: "white-132", text: "\"Can you make this sound warmer?\"", type: 'white' as const },
  { id: "white-133", text: "\"Can you make this shorter?\"", type: 'white' as const },
  { id: "white-134", text: "\"Can you make this sound like I actually care?\"", type: 'white' as const },
  { id: "white-135", text: "\"Overall, great call!\"", type: 'white' as const },
  { id: "white-136", text: "listening to myself say \"How does that feel?\" seventeen times", type: 'white' as const },
  { id: "white-137", text: "pretending I totally don't say \"absolutely\" every thirty seconds", type: 'white' as const },
  { id: "white-138", text: "discovering my customer service voice", type: 'white' as const },
  { id: "white-139", text: "one accidental thirty-second pause", type: 'white' as const },
  { id: "white-140", text: "fake confidence in my coaching voice", type: 'white' as const },
  { id: "white-141", text: "constructive feedback I wasn't emotionally prepared to receive", type: 'white' as const },
  { id: "white-142", text: "wondering if anyone noticed I forgot to ask an open-ended question", type: 'white' as const },
  { id: "white-143", text: "my favorite part of the call being when it ended", type: 'white' as const },
  { id: "white-144", text: "trying to sound natural while reading my notes", type: 'white' as const },
  { id: "white-145", text: "\"Is there anything else I can support you with today?\"", type: 'white' as const },
  { id: "white-146", text: "realizing I say \"perfect\" after literally everything", type: 'white' as const },
  { id: "white-147", text: "one awkward goodbye that lasted two minutes", type: 'white' as const },
  { id: "white-148", text: "my peer reviewer hearing me chew ice", type: 'white' as const },
  { id: "white-149", text: "color-coding my anxiety", type: 'white' as const },
  { id: "white-150", text: "filtering the Mission (Impossible) Tracker until it hurts less", type: 'white' as const },
  { id: "white-151", text: "one student destroying my entire dashboard", type: 'white' as const },
  { id: "white-152", text: "another red cell ruining my morning", type: 'white' as const },
  { id: "white-153", text: "Ctrl+Z as a coping mechanism", type: 'white' as const },
  { id: "white-154", text: "one miracle before month-end", type: 'white' as const },
  { id: "white-155", text: "pretending the metrics don't refresh tomorrow", type: 'white' as const },
  { id: "white-156", text: "one student hanging on by exactly one CU", type: 'white' as const },
  { id: "white-157", text: "wondering if airport Starbucks counts as a business expense", type: 'white' as const },
  { id: "white-158", text: "surviving an entire Summit on free hotel breakfast", type: 'white' as const },
  { id: "white-159", text: "keeping every receipt because Finance scares me", type: 'white' as const },
  { id: "white-160", text: "accidentally buying the $8 bottle of water", type: 'white' as const },
  { id: "white-161", text: "one suspiciously expensive Uber receipt", type: 'white' as const },
  { id: "white-162", text: "convincing myself the dessert was work-related", type: 'white' as const },
  { id: "white-163", text: "expensing snacks like my career depends on it", type: 'white' as const },
  { id: "white-164", text: "one conference tote bag I'll never use", type: 'white' as const },
  { id: "white-165", text: "eating three cookies because they were free", type: 'white' as const },
  { id: "white-166", text: "one breakout room that immediately went off the rails", type: 'white' as const },
  { id: "white-167", text: "emotionally investing in my buddy team", type: 'white' as const },
  { id: "white-168", text: "Glowbert's HR file", type: 'white' as const },
  { id: "white-169", text: "accidentally becoming the discussion leader", type: 'white' as const },
  { id: "white-170", text: "mandatory fun that was actually kind of fun", type: 'white' as const },
  { id: "white-171", text: "trusting ChatGPT just a little too much", type: 'white' as const },
  { id: "white-172", text: "asking AI to write an email, then asking AI what the email means", type: 'white' as const },
  { id: "white-173", text: "ChatGPT making me sound like I deserve a promotion", type: 'white' as const },
  { id: "white-174", text: "Claude roasting my PowerPoint", type: 'white' as const },
  { id: "white-175", text: "one mysteriously disappearing course", type: 'white' as const },
  { id: "white-176", text: "another course version nobody asked for", type: 'white' as const },
  { id: "white-177", text: "a course version from three migrations ago", type: 'white' as const },
  { id: "white-178", text: "one student with six versions of the same class", type: 'white' as const },
  { id: "white-179", text: "the magical reappearing course", type: 'white' as const },
  { id: "white-180", text: "a degree plan held together with duct tape", type: 'white' as const },
  { id: "white-181", text: "admin time", type: 'white' as const },
  { id: "white-182", text: "a perfectly documented SRM note", type: 'white' as const },
  { id: "white-183", text: "another attempted contact", type: 'white' as const },
  { id: "white-184", text: "one beautifully written call note", type: 'white' as const },
  { id: "white-185", text: "my seventh outreach attempt", type: 'white' as const },
  { id: "white-186", text: "a surprise graduation call", type: 'white' as const },
  { id: "white-187", text: "one perfectly timed \"Congratulations!\"", type: 'white' as const },
  { id: "white-188", text: "a student who actually answered the phone", type: 'white' as const },
  { id: "white-189", text: "my entire caseload needing me at once", type: 'white' as const },
  { id: "white-190", text: "Ignoring The Weekly Perch", type: 'white' as const },
  { id: "white-191", text: "one suspiciously enthusiastic icebreaker", type: 'white' as const },
  { id: "white-192", text: "another breakout room", type: 'white' as const },
  { id: "white-193", text: "accidental team bonding", type: 'white' as const },
  { id: "white-194", text: "mandatory collaboration", type: 'white' as const },
  { id: "white-195", text: "one Week 1 student who somehow finished the entire term", type: 'white' as const },
  { id: "white-196", text: "The Weekly Perch I definitely read", type: 'white' as const },
  { id: "white-197", text: "one Smart Owl rabbit hole", type: 'white' as const },
  { id: "white-198", text: "\"Let's see what AI thinks.\"", type: 'white' as const },
  { id: "white-199", text: "a student who actually followed the pacing plan", type: 'white' as const },
  { id: "white-200", text: "one perfectly timed graduation confetti email", type: 'white' as const },
  { id: "white-201", text: "weaponized \"Reply All\"", type: 'white' as const },
  { id: "white-202", text: "pretending to look busy until 4:59 PM", type: 'white' as const },
  { id: "white-203", text: "surviving entirely on caffeine and false confidence", type: 'white' as const },
  { id: "white-204", text: "one more mandatory \"optional\" meeting", type: 'white' as const },
  { id: "white-205", text: "a PowerPoint with 87 unread speaker notes", type: 'white' as const },
  { id: "white-206", text: "professional gaslighting", type: 'white' as const },
  { id: "white-207", text: "saying \"Absolutely!\" before I heard the question", type: 'white' as const },
  { id: "white-208", text: "pretending my camera is broken on purpose", type: 'white' as const },
  { id: "white-209", text: "one aggressively unnecessary recurring meeting", type: 'white' as const },
  { id: "white-210", text: "getting promoted to \"additional responsibilities\"", type: 'white' as const },
  { id: "white-211", text: "doing tomorrow's work with today's motivation", type: 'white' as const },
  { id: "white-212", text: "one Outlook reminder away from a career change", type: 'white' as const },
  { id: "white-213", text: "strategically appearing \"Available\" in Teams", type: 'white' as const },
  { id: "white-214", text: "a meeting about scheduling another meeting", type: 'white' as const },
  { id: "white-215", text: "\"This shouldn't take long.\"", type: 'white' as const },
  { id: "white-216", text: "pretending I didn't see that Teams message", type: 'white' as const },
  { id: "white-217", text: "volunteering someone else", type: 'white' as const },
  { id: "white-218", text: "one email chain that should have died three days ago", type: 'white' as const },
  { id: "white-219", text: "quietly updating my résumé during a Teams meeting", type: 'white' as const },
  { id: "white-220", text: "living, laughing, leaving the meeting", type: 'white' as const },
  { id: "white-221", text: "my fifth personality of the workday", type: 'white' as const },
  { id: "white-222", text: "pretending this aligns with my career goals", type: 'white' as const },
  { id: "white-223", text: "one PTO request away from inner peace", type: 'white' as const },
  { id: "white-224", text: "working hard or hardly Outlooking", type: 'white' as const },
  { id: "white-225", text: "the illusion of work-life balance", type: 'white' as const },
  { id: "white-226", text: "the meeting before the meeting", type: 'white' as const }
]
